### ISSUE TITLE
Using google-auth instead of google_auth_httplib2?

### ISSUE THREAD

**Issue by tobiasbp** [christippett/hangouts-chat-util#1]
Hello there..

Great looking library.  I noticed you are using google_auth_httplib2. However, Google says the library is not to be used:
https://pypi.org/project/google-auth-httplib2/

"httplib has lots of problems such as lack of threadsafety and insecure usage of TLS. Using it is highly discouraged. This library is intended to help existing users of oauth2client migrate to google-auth."

Are you considering a switch to 'google-auth'? 
https://pypi.org/project/google-auth/

Thanks,
Tobias

**Comment by christippett** [comment]
Hey Tobias. Thanks for the heads up.. I'll look at refactoring the code to use google-auth.

**Comment by christippett** [comment]
Hey @tobiasbp, just had a deeper look into this. The warning note on the `google-auth-httplib2` library refers to `httplib` and not `httplib2`. Google's own Python samples for using the Hangouts Chat API also use the `google-auth-httplib2` library (it's where I originally came across it). I don't see a problem with using it.

Your suggestion did make me look into `google-auth` a bit more though and I've refactored how the `HangoutsChatAPI` class gets its credentials.

**Comment by tobiasbp** [comment]
Changes looking good.

Do you not feel the text "This library is intended to help existing users of oauth2client migrate to google-auth." indicates that Google thinks developers should not use google_auth_httplib2 but use google-auth exclusively?
